name: template
description: "template"

version: 1.0.0+1
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  get_it: ^8.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.14

flutter:
  uses-material-design: true




























  #


